# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_MACH_MESON6) += \
	meson6-atv1200.dtb
dtb-$(CONFIG_MACH_MESON8) += \
	meson8-minix-neo-x8.dtb \
	meson8-tronsmart-s82.dtb \
	meson8b-ec100.dtb \
	meson8b-mxq.dtb \
	meson8b-odroidc1.dtb \
	meson8b-onecloud.dtb \
	meson8b-onecloud-v13.dtb \
	meson8b-onecloud-v14.dtb \
	meson8b-onecloud-v15.dtb \
	meson8b-onecloud-oc.dtb \
	meson8b-onecloud-oc-v13.dtb \
	meson8b-onecloud-oc-v14.dtb \
	meson8b-onecloud-oc-v15.dtb \
	meson8b-onecloud-otg.dtb \
	meson8b-onecloud-role-switch.dtb \
	meson8m2-m8s.dtb \
	meson8m2-mxiii.dtb \
	meson8m2-mxiii-plus.dtb \
	meson8m2-wetek-core.dtb
